# Generated by Django 5.2.12 on 2026-04-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_join_code_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
