# Generated by Django 5.2.12 on 2026-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='join_role',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
