# Generated by Django 5.2.12 on 2026-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_team_join_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='join_role',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
    ]
