# Generated by Django 5.2.12 on 2026-04-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_join_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='code_expires_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='code_is_active',
        ),
        migrations.RemoveField(
            model_name='team',
            name='join_code',
        ),
        migrations.RemoveField(
            model_name='team',
            name='join_role',
        ),
    ]
