# Generated by Django 5.2.12 on 2026-04-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_manager_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('MEMBER', 'Member')], max_length=50),
        ),
    ]
