# Generated by Django 5.2.12 on 2026-04-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_initial'),
        ('organizations', '0003_alter_organization_options'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
