# Generated by Django 5.2.12 on 2026-04-15 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activitylog_organization_alter_activitylog_project'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
