# Generated by Django 5.2.12 on 2026-04-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at']},
        ),
    ]
