# Generated by Django 5.2.12 on 2026-04-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_join_code_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='join_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('DEVELOPER', 'Developer')], default='DEVELOPER', max_length=20),
        ),
    ]
