# Generated by Django 5.2.12 on 2026-04-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_join_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='organizations.organizationmembership'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='join_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('MEMBER', 'Member')], max_length=20),
        ),
    ]
