# Generated by Django 5.2.12 on 2026-04-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationmembership_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='code_expires_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='code_is_active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='join_code',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='join_role',
        ),
    ]
