# Generated by Django 5.2.12 on 2026-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_organization_code_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('MEMBER', 'Member')], max_length=20),
        ),
    ]
