# Generated by Django 5.2.12 on 2026-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organizationmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('LEAD', 'Lead'), ('MEMBER', 'Member')], max_length=20),
        ),
    ]
